### DISCUSSION TITLE
Dashboard for integration?

### DISCUSSION THREAD

**Discussion by trib22** [TypQxQ/Sigenergy-Local-Modbus#51] [Ideas]
The initial integration had an extensive dashboard that showed pretty much everything going on and offered a small set of controls. It was useful for gaining an understanding of how the integration worked.

Are there plans to produce a dashboard for this version, or should I go ahead and hack together something from the earlier code?

Happy to share/contribute.

**Comment by TypQxQ** [comment]
Because everything is grouped under Device, I didn't think it necessary for such an extensive dashboard as the old one.
Here is a small test I have, you are welcome to make a better one and publish it in [Discussions ](https://github.com/TypQxQ/HACS-Sigenergy-Local-Modbus/discussions/categories/show-and-tell)😄 
```
views:
  - title: Overview
    icon: mdi:sun-compass
    cards:
      - type: vertical-stack
        cards:
          - show_name: false
            show_icon: true
            show_state: false
            type: glance
            entities:
              - entity: sensor.sigen_plant_consumed_power
              - entity: binary_sensor.sigen_plant_pv_generating
                name: PV Generating
                icon: mdi:solar-power
              - entity: binary_sensor.sigen_plant_battery_charging
                name: Battery charging
                icon: mdi:battery-positive
              - entity: binary_sensor.sigen_plant_battery_discharging
                name: Battery discharging
                icon: mdi:battery-negative
              - entity: binary_sensor.sigen_plant_exporting_to_grid
                name: Exporting to grid
                icon: mdi:transmission-tower-import
              - entity: binary_sensor.sigen_plant_importing_from_grid
                name: Importing from grid
                icon: mdi:transmission-tower-export
            columns: 6
            state_color: true
          - show_name: false
            show_icon: false
            show_state: true
            type: glance
            entities:
              - entity: sensor.sigen_plant_consumed_power
              - entity: sensor.sigen_plant_pv_power
              - entity: sensor.sigen_plant_battery_state_of_charge
              - entity: sensor.sigen_plant_battery_power
              - entity: sensor.sigen_plant_grid_export_power
              - entity: sensor.sigen_plant_grid_import_power
            columns: 6
            state_color: true
          - show_name: false
            show_icon: false
            show_state: true
            type: glance
            entities:
              - entity: sensor.sigen_plant_daily_consumed_energy
              - entity: sensor.sigen_plant_daily_pv_energy
              - entity: sensor.sigen_plant_daily_battery_charge_energy
              - entity: sensor.sigen_plant_daily_battery_discharge_energy
              - entity: sensor.sigen_plant_daily_grid_export_energy
              - entity: sensor.sigen_plant_daily_grid_import_energy
            columns: 6
            state_color: false
            title: Daily
          - show_name: false
            show_icon: false
            show_state: true
            type: glance
            entities:
              - entity: sensor.sigen_plant_consumed_power
              - entity: sensor.sigen_plant_pv_power
              - entity: sensor.sigen_plant_battery_state_of_charge
              - entity: sensor.sigen_plant_battery_power
              - entity: sensor.sigen_plant_grid_export_power
              - entity: sensor.sigen_plant_grid_import_power
            columns: 6
            state_color: true
            title: Lifetime
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.sigen_plant_battery_state_of_charge
            min: 0
            max: 100
            severity:
              green: 30
              yellow: 10
              red: 0
            name: Battery
          - type: entities
            entities:
              - entity: sensor.sigen_plant_battery_power
                icon: mdi:battery-charging
              - entity: sensor.sigen_inverter_battery_average_cell_temperature
                name: Average cell temperature
                secondary_info: none
                icon: ''
              - entity: sensor.sigen_inverter_pcs_internal_temperature
                name: Inverter temperature
                secondary_info: none
      - chart_type: line
        period: 5minute
        type: statistics-graph
        entities:
          - sensor.sigen_plant_pv_power
          - sensor.sigen_plant_battery_power
          - sensor.sigen_plant_grid_import_power
          - sensor.sigen_plant_grid_export_power
          - sensor.sigen_plant_consumed_power
        stat_types:
          - mean
        title: Power distribution last 24 hours
        hide_legend: false
        logarithmic_scale: false
        days_to_show: 1
      - chart_type: line
        period: hour
        type: statistics-graph
        entities:
          - sensor.sigen_plant_pv_power
          - sensor.sigen_inverter_pv1_power
          - sensor.sigen_inverter_pv2_power
          - sensor.sigen_inverter_pv3_power
          - sensor.sigen_inverter_pv4_power
        stat_types:
          - mean
        days_to_show: 2
        title: Solar production last 48h
        logarithmic_scale: false
      - type: energy-distribution
        link_dashboard: true
    badges:
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_plant_general_alarm_1
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_plant_general_alarm_1
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_plant_general_alarm_2
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_plant_general_alarm_2
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_plant_general_alarm_3
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_plant_general_alarm_3
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_plant_general_alarm_4
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_plant_general_alarm_4
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_inverter_alarm_1
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_inverter_alarm_1
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_inverter_alarm_2
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_inverter_alarm_2
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_inverter_alarm_3
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_inverter_alarm_3
            state_not: No Alarms
      - type: entity
        show_name: false
        show_state: true
        show_icon: true
        entity: sensor.sigen_inverter_alarm_4
        color: red
        visibility:
          - condition: state
            entity: sensor.sigen_inverter_alarm_4
            state_not: No Alarms
title: PV System

```
