### DISCUSSION TITLE
Stopping the battery discharge with Intelligent Octopus Go

### DISCUSSION THREAD

**Discussion by CoLyn381** [TypQxQ/Sigenergy-Local-Modbus#73] [Troubleshooting] [answered]
With the latest Intelligent Octopus Go dynamic tariff and the Ohme Home Pro you get 6 hours of off peak between 23.30 and 05.30 but this tariff works with the national grid and Octopus can allocate charging periods anytime and also change them anytime so pre setting the corresponding charge times in the Sigen app can be challenging with these random changes. So any cheap rate periods that are given between 05.30-23.30 need to be matched as charging periods in the Sigen app so as not to discharge the battery as the EV load is seen as the house load.
I in conjunction with my installers electrician have tried rearranging the consumer unit cabling to separate the EV load and position the Sigen CT before the EV load but the Sigen meter sensor just doesn't like this and will only work on the meter tail. I've also tried the second CT in parallel but in reverse on the EV load but yet again the Sigen meter sensor doesn't like this as the data on both is erratic and even imports from the grid when only normal house loads are present. Hence now trying the software route and need some guidance.
I'm new to all of this but I have HA, Modbus, HACS, Octopus Energy, Ohme Home Pro Charge unit and of course this Sigenergy Integration all setup. I now need to create an automation that will trigger and do the action. Doing the trigger doesn't seem to be problem as I can create the Octopus energy rate. The problem that I'm having is the Action for the Sigenergy system. What I would like is to do is turn on the Inverter Charging mode when the 7p rate is detected, however there seems to be only one Acton with the Sigen_Plant to turn on or off.
Would anyone be able to help me with this project to create a working Automation? Many Thanks.

**Comment by TypQxQ** [comment]
I think you want to change mode like this. First you have to enable read-write in integration settings and then enable the switch.
They are disabled by default because of security concerns and possibility to do damage.

![image](https://github.com/user-attachments/assets/f5b3ec52-01d3-4bdd-9932-8a0fa465a04d)

**Reply by CoLyn381** [reply]
Thanks.
I can't find a read-write in the integrated settings but I have looked at all the disabled entities and I have enabled some that I thought may help but so far having no luck for the Action side, i.e. turn on Charging. Using the Sigen plant just shows two actions that you can use?

**Comment by TypQxQ** [comment]
Sorry but I don’t understand. Please show with pictures.

**Reply by CoLyn381** [reply]
> Sorry but I don’t understand. Please show with pictures. 

For the Devices as you can see the Action selection is limited.![Screenshot_2025-05-14-14-36-58-37_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/4c5d6a22-0561-463c-9952-5ce973411fde)

**Reply by TypQxQ** [reply]
When building automation it's best to try it manually first. For selecting Mode you need to do like this I think. Never done it myself though.

![image](https://github.com/user-attachments/assets/a36e8c63-1ec3-4a05-b4dd-759e5aad03ad)

**Reply by andyp421** [reply]
Hi @CoLyn381 
Did you ever manage to configure this?   I had my system installed today and I want to do exactly the same thing but not finding much info on how to do it.   I have Modbus etc all enabled but I just cant figure out how to charge the battery when IOG intelligent dispatching is active.    
Thanks
Andy

**Reply by CoLyn381** [reply, marked as answer]
@andyp421 Hello Andy. No I couldn't achieve controlling the Sigenergy system, it's mostly only for visual data displays.
I changed my Consumer Unit cupboard wiring so that the Sigen CT couldn't see the EV load. This was fairly simple by adding a £6 single Henley block and two short 16mm² cables and an electrician for 1 hour.
![IMG20250515194010 (1).jpg](https://github.com/user-attachments/assets/0a1d6f92-222d-4eff-955d-35d0d1cd14f3)

**Reply by andyp421** [reply]
Thats a pity.   Thanks for the fast reply too

**Reply by andyp421** [reply]
So, just to close this off - I found a post on the Sigenergy FB group that has solved this for me.   (Colin had also posted the wiring diagram above on the same thread.)

I've now had the EV charger wired into the smart port on the gateway and this has solved the issue for me.    You have to set an auto schedule for the smart device but then it will not discharge the battery when charging unless you select Battery Boost.     It's not 100% fool proof on AI mode because I've seen load switch for a few seconds to battery but it's working.   I am currently taking advantage of the octopus free electricity hour and the battery is staying nice and full whilst the car is charging.

Hope that helps someone.  YMMV as always

**Comment by reedy** [comment]
Ignoring the issues I saw in https://github.com/TypQxQ/Sigenergy-Local-Modbus/issues/223...

And it's using `{{DEVICE_ID}}` because of the changes in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v17.0.0-beta.1 which are coming...

When IO dispatching is on, charge the battery. When it goes off, go to self consumption...

<img width="1596" height="587" alt="Screenshot 2025-09-24 at 21 42 49" src="https://github.com/user-attachments/assets/a4fb1044-a772-4a69-87ae-e19c5d466b26" />

```yaml
alias: Octopus Energy - Put Sigen into Charge when Dispatching
description: ""
triggers:
  - trigger: state
    entity_id:
      - >-
        binary_sensor.octopus_energy_{{DEVICE_ID}}_intelligent_dispatching
    from: null
    to: "on"
conditions: []
actions:
  - device_id: {{DEVICE_ID}}
    domain: select
    entity_id: {{ENTITY_ID}}
    type: select_option
    option: Command Charging (Grid First)
mode: single
```

<img width="1603" height="639" alt="Screenshot 2025-09-24 at 21 43 02" src="https://github.com/user-attachments/assets/7b4660cf-fc6d-4fd1-8321-2b2a118676c3" />

```yaml
alias: Octopus Energy - Put Sigen into Maximum Self Consumption when Not Dispatching
description: ""
triggers:
  - trigger: state
    entity_id:
      - >-
        binary_sensor.octopus_energy_{{DEVICE_ID}}_intelligent_dispatching
    from: null
    to: "off"
conditions: []
actions:
  - device_id: {{DEVICE_ID}}
    domain: select
    entity_id: {{ENTITY_ID}}
    type: select_option
    option: Maximum Self Consumption
mode: single
```

It may be possible to make blueprints for these...
