### ISSUE TITLE
Correct Integration With Predbat

### ISSUE THREAD

**Issue by Evaske** [TypQxQ/Sigenergy-Local-Modbus#74]
Hi,

Thanks for the work on this integration. I've just recently swapped over to this new integration instead of the older version and just wanted to check I was doing the Predbat integration correctly.

For predbat to talk to the system it is making use of `modbus.write_register` which worked fine with the old integration. With the new integration Home Assistant knows nothing of `modbus` and so to get it to work I had to add the following to my configuration.yaml:

```
modbus:
  - name: Sigen
    type: tcp
    host: 192.168.0.167
    port: 502
    switches:
      - name: DummySwitch
        address: 13
        write_type: coil
```

Obviously this integration is already using modbus in the background so I shouldn't in theory have needed to add that entry to my configuration.yaml. What is the method to actually talk to the battery using the new integration.

This is part of the current code that is being used by Predbat from their docs that was mainly aimed at the old integration:

```
- id: "automation_sigen_ess_max_discharging_limit_input_number_action"
        alias: "sigen ESS max discharging limit input number action"
        description: "Sigen ESS max discharging limit action for batpred"
        triggers:
          - trigger: state
            entity_id: input_number.discharge_rate
        action:
          - action: modbus.write_register
            data_template:
              hub: Sigen
              slave: 247
              address: 40034
              value:
                - >-
                  0
                - >-
                  {{ states('input_number.discharge_rate') |
                  round(0) | int }}
        mode: single
```

Without the modbus entry in to configuration.yaml, there is a home assistant log entry that modbus doesn't exist.

**Comment by TypQxQ** [comment]
You shouldn't use both integrations together because the poll intervall would be to small and Sigenergy give errors.

**Comment by TypQxQ** [comment]
Here is some configuration I have been able to write together.
Please evaluate and if it works, I'll make it more readily available inside the FAQ and send it to PredBat.

Home Assistant configuration.yaml additions:
```
template:
  - sensor:
    - name: "Sigen Plant Battery Power W"
      unique_id: sigen_plant_battery_power_w
      state: >
        {% set power = states('sensor.sigen_plant_battery_power') | float(0) %}
        {{ (power * -1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
    - name: "Sigen Plant Consumed Power W"
      unique_id: sigen_plant_consumed_power_w
      state: >
        {% set power = states('sensor.sigen_plant_consumed_power') | float(0) %}
        {{ (power * 1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
    - name: "Sigen Plant Grid Active Power W"
      unique_id: sigen_plant_grid_active_power_w
      state: >
        {% set power = states('sensor.sigen_plant_grid_active_power') | float(0) %}
        {{ (power * -1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
    - name: "Sigen Plant PV Power W"
      unique_id: sigen_plant_pv_power_w
      state: >
        {% set power = states('sensor.sigen_plant_pv_power') | float(0) %}
        {{ (power * 1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
    - name: "Sigen Plant ESS Rated Discharging Power"
      unique_id: sigen_plant_ess_rated_discharging_power_w
      state: >
        {% set power = states('sensor.sigen_plant_ess_rated_discharging_power') | float(0) %}
        {{ (power * 1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
    - name: "Sigen Plant ESS Rated Charging Power"
      unique_id: sigen_plant_ess_rated_charging_power_w
      state: >
        {% set power = states('sensor.sigen_plant_ess_rated_charging_power') | float(0) %}
        {{ (power * 1000) | round(0) }}
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement

input_number:
  sigen_plant_ess_max_discharging_limit_w:
    name: Sigen Plant ESS Max Discharging Limit W
    min: 0
    max: 500000
    step: 1
    mode: box
  sigen_plant_ess_max_charging_limit_w:
    name: Sigen Plant ESS Max Charging Limit W
    min: 0
    max: 500000
    step: 1
    mode: box

automation:
  - id: "automation_sigen_plant_ess_max_charging_limit_w_input_number_action"
    alias: "Sigen Plant ESS Max Charging Limit W input number action"
    description: "Sigen Plant ESS Max Charging Limit W action for BatPred"
    triggers:
      - trigger: state
        entity_id: input_number.sigen_plant_ess_max_charging_limit_w
    action:
      - action: number.set_value
        target:
          entity_id: number.sigen_plant_ess_max_charging_limit
        data:
          value: "{{ (states('input_number.sigen_plant_ess_max_charging_limit_w') | float(0)) / 1000 }}"
    mode: single
  - id: "automation_sigen_plant_ess_max_discharging_limit_w_input_number_action"
    alias: "Sigen Plant ESS Max Discharging Limit W input number action"
    description: "Sigen Plant ESS Max Discharging Limit W action for BatPred"
    triggers:
      - trigger: state
        entity_id: input_number.sigen_plant_ess_max_discharging_limit_w
    action:
      - action: number.set_value
        target:
          entity_id: number.sigen_plant_ess_max_discharging_limit
        data:
          value: "{{ (states('input_number.sigen_plant_ess_max_discharging_limit_w') | float(0)) / 1000 }}"
    mode: single
```

BatPred apps.yaml example file:
```
# ------------------------------------------------------------------
# This is an example configuration, please modify it
# ------------------------------------------------------------------
---
pred_bat:
  module: predbat
  class: PredBat

  # Sets the prefix for all created entities in HA - only change if you want to run more than once instance
  prefix: predbat

  # XXX: This is a configuration template, delete this line once you edit your configuration
  # template: True

  # Timezone to work in
  timezone: Europe/Stockholm

  # Currency, symbol for main currency second symbol for 1/100s e.g. $ c or £ p or e c
  currency_symbols:
    - "SEK"
    - "öre"

  # Number of threads to use in plan calculation
  # Can be auto for automatic, 0 for off or values 1-N for a fixed number
  threads: auto

  # If you are using Predbat outside of HA then set the HA URL and Key (long lived access token here)
  #ha_url: 'http://homeassistant.local:8123'
  #ha_key: 'xxx'

  # Sets the maximum period of zero load before the gap is filled, default 30 minutes
  # To disable set it to 1440
  load_filter_threshold: 30

  #
  # Sensors, currently more than one can be specified and they will be summed up automatically
  # however multiple inverters are already summed up to plant when set up properly.
  #
  inverter_type: "SIG"
  num_inverters: 1
  #
  # Controls/status - All Sigenergy inverters are summed under a plant.
  #
  load_today:
    - sensor.sigen_plant_daily_consumed_energy
  import_today:
    - sensor.sigen_plant_daily_grid_import_energy
  export_today:
    - sensor.sigen_plant_daily_grid_export_energy
  pv_today:
    - sensor.sigen_plant_daily_pv_energy
  battery_power:
    - sensor.sigen_plant_battery_power_w
  pv_power:
    - sensor.sigen_plant_pv_power_w
  load_power:
    - sensor.sigen_plant_consumed_power_w
  grid_power:
    - sensor.sigen_plant_grid_active_power_w
  soc_percent:
    - sensor.sigen_plant_battery_state_of_charge
  soc_max:
    - sensor.sigen_plant_rated_energy_capacity
  battery_temperature:
    - sensor.sigen_inverter_battery_average_cell_temperature

  # Services to control the inverter
  # The Sigen Plant has to be configured as not Read-Only
  # and the Remote EMS Plant option has to be active.
  charge_start_service:
    - service: select.select_option
      entity_id: "select.sigen_plant_remote_ems_control_mode"
      option: "Command Charging (PV First)"
  charge_stop_service:
    - service: select.select_option
      entity_id: "select.sigen_plant_remote_ems_control_mode"
      option: "Maximum Self Consumption"
  discharge_start_service:
    - service: select.select_option
      entity_id: "select.sigen_plant_remote_ems_control_mode"
      option: "Command Discharging (PV First)"
  discharge_stop_service:
    - service: select.select_option
      entity_id: "select.sigen_plant_remote_ems_control_mode"
      option: "Maximum Self Consumption"
  charge_freeze_service:
    - service: number.set_value
      entity_id: "number.sigen_plant_ess_max_charging_limit"
      value: 1
  discharge_freeze_service:
    - service: number.set_value
      entity_id: "number.sigen_plant_ess_max_discharging_limit"
      value: 1

  # Load forecast can be used to add to the historical load data (heat-pump)
  # To link to Predheat
  # Data must be in the format of 'last_updated' timestamp and 'energy' for incrementing kWh
  #load_forecast:
  #  - predheat.heat_energy$external
  #

  # Controls/status - must by 1 per inverter
  # Run balance inverters every N seconds (0=disabled) - only for multi-inverter
  balance_inverters_seconds: 60

  # Only gen3 supports discharge target SOC, will be ignored if not present
  # discharge_target_soc:
  #   - number.givtcp_{geserial}_discharge_target_soc_1
  #   - number.givtcp2_{geserial2}_discharge_target_soc_1

  # Battery temperature sensor per inverter, used outside REST mode to get current temperature
  #
  #battery_temperature:
  # - sensor.givtcp_battery_stack_1_bms_temperature
  # - sensor.givtcp2_battery_stack_1_bms_temperature

  # Battery temperature history, only one for modelling, used to predict future temperature
  #
  #battery_temperature_history: sensor.givtcp_battery_stack_1_bms_temperature

  # Battery temperature charge adjustment curve
  # Specific in C which is a multiple of the battery capacity
  # e.g. 0.33 C is 33% of the battery capacity
  # values unspecified will be assumed to be 1.0 hence rate is capped by max charge rate
  #battery_temperature_charge_curve:
  #  19: 0.33
  #  18: 0.33
  #  17: 0.33
  #  16: 0.33
  #  15: 0.33
  #  14: 0.33
  #  13: 0.33
  #  12: 0.33
  #  11: 0.33
  #  10: 0.25
  #  9: 0.25
  #  8: 0.25
  #  7: 0.25
  #  6: 0.25
  #  5: 0.25
  #  4: 0.25
  #  3: 0.25
  #  2: 0.25
  #  1: 0.15
  #  0: 0.00

  # Inverter max AC limit (one per inverter). E.g for a 3.6kw inverter set to 3600
  # If you have a second inverter for PV only please add the two values together
  inverter_limit:
    - 15000

  # Export limit is a software limit set on your inverter that prevents exporting above a given level
  # When enabled Predbat will model this limit
  export_limit:
    - 13000

  # The maximum rate the inverter can charge and discharge the battery can be overwritten, this will change
  # the register programming and thus cap the max rates. The default is to use the maximum supported rates (recommended)
  #
  inverter_limit_charge:
    - sensor.sigen_plant_ess_rated_charging_power_w
  inverter_limit_discharge:
    - sensor.sigen_plant_ess_rated_discharging_power_w

  # calculations to tell predbat the actual charge/discharge power of the inverter
  charge_rate:
    - input_number.sigen_plant_ess_max_charging_limit_w
  discharge_rate:
    - input_number.sigen_plant_ess_max_discharging_limit_w
  battery_rate_max:
    - sensor.sigen_plant_ess_rated_charging_power_w # Rated charging is lower than discharging.

  # Some inverters don't turn off when the rate is set to 0, still charge or discharge at around 200w
  # The value can be set here in watts to model this (doesn't change operation)
  inverter_battery_rate_min:
    - 1

  # Workaround to limit the maximum reserve setting, some inverters won't allow 100% to be set
  # Comment out if your inverter allows 100%
  # inverter_reserve_max: 98

  # Some batteries tail off their charge rate at high soc%
  # enter the charging curve here as a % of the max charge rate for each soc percentage.
  # the default is 1.0 (full power)
  # The example below is from GE 9.5kwh battery with latest firmware and gen1 inverter
  #
  # Predbat can compute this curve automatically if you have enough data, restart the add-on and look in the logfile for the data
  # once set here Predbat will no longer re-compute the curve.
  # Can also be set to 'auto' to just use the calculation curve, not recommended if you are using low power charging mode.
  #battery_charge_power_curve:
  #  91 : 0.91
  #  92 : 0.81
  #  93 : 0.71
  #  94 : 0.62
  #  95 : 0.52
  #  96 : 0.43
  #  97 : 0.33
  #  98 : 0.24
  #  99 : 0.24
  #  100 : 0.24
  #battery_discharge_power_curve:
  #  4 : 1.0

  # Inverter clock skew in minutes, e.g. 1 means it's 1 minute fast and -1 is 1 minute slow
  # Separate start and end options are applied to the start and end time windows, mostly as you want to start late (not early) and finish early (not late)
  # Separate discharge skew for discharge windows only
  inverter_clock_skew_start: 0
  inverter_clock_skew_end: 0
  inverter_clock_skew_discharge_start: 0
  inverter_clock_skew_discharge_end: 0

  # Clock skew adjusts the Appdaemon time
  # This is the time that Predbat takes actions like starting discharge/charging
  # Only use this for workarounds if your inverter time is correct but Predbat is somehow wrong (AppDaemon issue)
  # 1 means add 1 minute to AppDaemon time, -1 takes it away
  clock_skew: 0

  # Solcast cloud interface, set this or the local interface below
  #solcast_host: 'https://api.solcast.com.au/'
  #solcast_api_key: 'xxxx'
  #solcast_poll_hours: 8

  # Set these to match solcast sensor names if not using the cloud interface
  # The regular expression (re:) makes the solcast bit optional
  # If these don't match find your own names in Home Assistant
  pv_forecast_today: re:(sensor.(solcast_|)(pv_forecast_|)forecast_today)
  pv_forecast_tomorrow: re:(sensor.(solcast_|)(pv_forecast_|)forecast_tomorrow)
  # pv_forecast_d3: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_3|d3))
  # pv_forecast_d4: re:(sensor.(solcast_|)(pv_forecast_|)forecast_(day_4|d4))

  # car_charging_energy defines an incrementing sensor which measures the charge added to your car
  # is used for car_charging_hold feature to filter out car charging from the previous load data
  # Automatically set to detect Wallbox and Zappi, if it doesn't match manually enter your sensor name
  # Also adjust car_charging_energy_scale if it's not in kwH to fix the units
  # car_charging_energy: "re:(sensor.myenergi_zappi_[0-9a-z]+_charge_added_session|sensor.wallbox_portal_added_energy)"

  # Defines the number of cars modelled by the system, set to 0 for no car
  num_cars: 0

  # car_charging_planned is set to a sensor which when positive indicates the car will charged in the upcoming low rate slots
  # This should not be needed if you use Intelligent Octopus slots which will take priority if enabled
  # The list of possible values is in car_charging_planned_response
  # Auto matches Zappi and Wallbox, or change it for your own
  # One entry per car
  # car_charging_planned:
  # - "re:(sensor.wallbox_portal_status_description|sensor.myenergi_zappi_[0-9a-z]+_plug_status)"

  # car_charging_planned_response:
  #   - "yes"
  #   - "on"
  #   - "true"
  #   - "connected"
  #   - "ev connected"
  #   - "charging"
  #   - "paused"
  #   - "waiting for car demand"
  #   - "waiting for ev"
  #   - "scheduled"
  #   - "enabled"
  #   - "latched"
  #   - "locked"
  #   - "plugged in"
  #   - "waiting"

  # In some cases car planning is difficult (e.g. Ohme with Intelligent doesn't report slots)
  # The car charging now can be set to a sensor to indicate the car is charging and to plan
  # for it to charge during this 30 minute slot
  #car_charging_now:
  #  - off

  # Positive responses for car_charging_now
  # car_charging_now_response:
  #   - "yes"
  #   - "on"
  #   - "true"

  # To make planned car charging more accurate, either using car_charging_planned or the Octopus Energy plugin,
  # specify your battery size in kwh, charge limit % and current car battery soc % sensors/values.
  # If you have Intelligent Octopus the battery size and limit will be extracted from the Octopus Energy plugin directly.
  # Set the car SOC% if you have it to give an accurate forecast of the cars battery levels.
  # One entry per car if you have multiple cars.
  #car_charging_battery_size:
  #  - 75
  #car_charging_limit:
  #  - 're:number.tsunami_charge_limit'
  #car_charging_soc:
  #  - 're:sensor.tsunami_battery'

  # One per car, when true only one car can charge at once, when False multiple cars can charge at once
  #car_charging_exclusive:
  #  - True

  # If you have Octopus intelligent, enable the intelligent slot information to add to pricing
  # Will automatically disable if not found, or comment out to disable fully
  # When enabled it overrides the 'car_charging_planned' feature and predict the car charging based on the intelligent plan (unless octopus intelligent charging is False)
  # This matches either the intelligent slot from the Octopus Plugin or from the Intelligent plugin
  # octopus_intelligent_slot: "re:(binary_sensor.octopus_energy([0-9a-z_]+|)_intelligent_dispatching)"
  # octopus_ready_time: "re:((select|time).octopus_energy_([0-9a-z_]+|)_intelligent_target_time)"
  # octopus_charge_limit: "re:(number.octopus_energy([0-9a-z_]+|)_intelligent_charge_limit)"

  # Example alternative configuration for Ohme integration release >=v0.6.1
  #octopus_intelligent_slot: 'binary_sensor.ohme_slot_active'
  #octopus_ready_time: 'time.ohme_target_time'
  #octopus_charge_limit: 'number.ohme_target_percent'

  # Set this to False if you use Octopus Intelligent slot for car planning but when on another tariff e.g. Agile
  #octopus_slot_low_rate: False

  # Carbon Intensity data from National grid
  # carbon_intensity: "re:(sensor.carbon_intensity_uk)"

  # Octopus saving session points to the saving session Sensor in the Octopus plugin, when enabled saving sessions will be at the assumed
  # Rate is read automatically from the add-in and converted to pence using the conversion rate below (default is 8)
  # octopus_saving_session: "re:(binary_sensor.octopus_energy([0-9a-z_]+|)_saving_session(s|))"
  # octopus_saving_session_octopoints_per_penny: 8

  # Octopus free session points to the free session Sensor in the Octopus plugin
  # Note: You must enable this event sensor in the Octopus Integration in Home Assistant for it to work
  # octopus_free_session: "re:(event.octopus_energy_([0-9a-z_]+|)_octoplus_free_electricity_session_events)"

  # Alternative scraper from Octopus web site if the above is not working
  # octopus_free_url: 'http://octopus.energy/free-electricity'

  # Energy rates
  # Please set one of these three, if multiple are set then Octopus is used first, second rates_import/rates_export and latest basic metric

  # Set import and export entity to point to the Octopus Energy plugin import and export sensors
  # automatically matches your meter number assuming you have only one (no need to edit the below)
  # Will be ignored if you don't have the sensor but will error if you do have one and it's incorrect
  # NOTE: To get detailed energy rates you need to go in and manually enable the following events in HA
  #       event.octopus_energy_electricity_xxxxxxxx_previous_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_current_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_next_day_rates
  # and if you have export enable:
  #       event.octopus_energy_electricity_xxxxxxxx_export_previous_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_export_current_day_rates
  #       event.octopus_energy_electricity_xxxxxxxx_export_next_day_rates
  # Predbat will automatically find the event. entities from the link below to the sensors
  # metric_octopus_import: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_rate)"
  # metric_octopus_export: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_export_current_rate)"

  # Nordpool energy sensor added from HACS. Example for Swedish prices
  metric_octopus_import: sensor.nordpool_kwh_se3_import
  metric_octopus_export: sensor.nordpool_kwh_se3_export

  # Standing charge in pounds, can be set to a sensor or manually entered (e.g. 0.50 is 50p)
  # The default below will pick up the standing charge from the Octopus Plugin
  # The standing charge only impacts the cost graphs and doesn't change the way Predbat plans
  # If you don't want to show the standing charge then just delete this line or set to zero
  # metric_standing_charge: "re:(sensor.(octopus_energy_|)electricity_[0-9a-z]+_[0-9a-z]+_current_standing_charge)"

  # Energy data service (https://github.com/MTrab/energidataservice)
  #metric_energidataservice_import: 'sensor.energi_data_service_import'
  #metric_energidataservice_export: 'sensor.energi_data_service_export'

  # Or set your actual rates across time for import and export
  # If start/end is missing it's assumed to be a fixed rate
  # Gaps are filled with zero rate
  #rates_import:
  #  -  start: "00:30:00"
  #     end: "04:30:00"
  #     rate: 7.5
  #  -  start: "04:30:00"
  #     end: "00:30:00"
  #     rate: 40.0
  #
  #rates_export:
  #  -  rate: 4.2

  # Can be used instead of the plugin to get import rates directly online
  # Overrides metric_octopus_import and rates_import
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-A/standard-unit-rates"
  # rates_import_octopus_url : "https://api.octopus.energy/v1/products/AGILE-BB-24-10-01/electricity-tariffs/E-1R-AGILE-BB-24-10-01-A/standard-unit-rates/"

  # Overrides metric_octopus_export and rates_export
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/FLUX-EXPORT-BB-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-BB-23-02-14-A/standard-unit-rates"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-A/standard-unit-rates/"
  # rates_export_octopus_url: "https://api.octopus.energy/v1/products/OUTGOING-FIX-12M-BB-23-02-09/electricity-tariffs/E-1R-OUTGOING-FIX-12M-BB-23-02-09-A/standard-unit-rates/"

  # Import rates can be overridden with rate_import_override
  # Export rates can be overridden with rate_export_override
  # Use the same format as above, but a date can be included if it just applies for a set day (e.g. Octopus power ups)
  # This will override even the Octopus plugin rates if enabled
  #
  #rates_import_override:
  # -  date: '2023-09-10'
  #    start: '14:00:00'
  #    end: '14:30:00'
  #    rate: 112
  #    load_scaling: 0.8

  # For pv estimate, leave blank for central estimate, or add 10 for 10% curve (worst case) or 90 or 90% curve (best case)
  # If you use 10 then disable pv_metric10_weight below
  # pv_estimate: 10

  # Days previous is the number of days back to find historical load data
  # Recommended is 7 to capture day of the week but 1 can also be used
  # if you have more history you could use 7 and 14 (in a list) but the standard data in HA only lasts 10 days
  days_previous:
    - 7

  # Days previous weight can be used to control the weighting of the previous load points, the values are multiplied by their
  # weights and then divided through by the total weight. E.g. if you used 1 and 0.5 then the first value would have 2/3rd of the weight and the second 1/3rd
  # Include one value for each days_previous value, each weighting on a separate line.
  # If any days_previous's that are not given a weighting they will assume a default weighting of 1.
  days_previous_weight:
    - 1

  # Number of hours forward to forecast, best left as-is unless you have specific reason
  forecast_hours: 48

  # Specify the devices that notifies are sent to, the default is 'notify' which goes to all
  #notify_devices:
  #  - mobile_app_treforsiphone12_2

  # Battery scaling makes the battery smaller (e.g. 0.9) or bigger than its reported
  # If you have an 80% DoD battery that falsely reports it's kwh then set it to 0.8 to report the real figures
  # One per inverter
  battery_scaling:
    - 1.0

  # Can be used to scale import and export data, used for workarounds
  import_export_scaling: 1.0

  # Export triggers:
  # For each trigger give a name, the minutes of export needed and the energy required in that time
  # Multiple triggers can be set at once so in total you could use too much energy if all run
  # Creates an entity called 'binary_sensor.predbat_export_trigger_<name>' which will be turned On when the condition is valid
  # connect this to your automation to start whatever you want to trigger
  export_triggers:
    - name: "large"
      minutes: 60
      energy: 1.0
    - name: "small"
      minutes: 15
      energy: 0.25

  # If you have a sensor that gives the energy consumed by your solar diverter then add it here
  # this will make the predictions more accurate. It should be an incrementing sensor, it can reset at midnight or not
  # It's assumed to be in Kwh but scaling can be applied if need be
  #iboost_energy_today: 'sensor.xxxxx'
  #iboost_energy_scaling: 1.0
  # Gas rates for comparison
  #metric_octopus_gas: 're:(sensor.(octopus_energy_|)gas_[0-9a-z]+_[0-9a-z]+_current_rate)'

  # Nordpool market energy rates
  #futurerate_url: 'https://dataportal-api.nordpoolgroup.com/api/DayAheadPrices?date=DATE&market=N2EX_DayAhead&deliveryArea=UK&currency=GBP'
  #futurerate_adjust_import: True
  #futurerate_adjust_export: False
  #futurerate_peak_start: "16:00:00"
  #futurerate_peak_end: "19:00:00"
  #futurerate_peak_premium_import: 14
  #futurerate_peak_premium_export: 6.5

  # Tariff comparison feature
  # Adjust this list to the tariffs you want to compare, include your current tariff also
  # Octopus region code (https://energy-stats.uk/dno-region-codes-explained/)
  #octopus_region: "A"
  #compare_list:
  #  - id: 'current'
  #    name: 'Current Tariff'
  #  - id: 'cap_seg'
  #    name: 'Price cap import/Seg export'
  #    rates_import:
  #       - rate: 24.86
  #    rates_export:
  #       - rate: 4.1
  #  - id: 'igo_fixed'
  #    name: 'Intelligent GO import/Fixed export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/INTELLI-BB-VAR-23-03-01/electricity-tariffs/E-1R-INTELLI-BB-VAR-23-03-01-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-BB-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-BB-24-10-26-{octopus_region}/standard-unit-rates/'
  #  - id: 'igo_agile'
  #    name: 'Intelligent GO import/Agile export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/INTELLI-BB-VAR-23-03-01/electricity-tariffs/E-1R-INTELLI-BB-VAR-23-03-01-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-{octopus_region}/standard-unit-rates/'
  #  - id: 'go_fixed'
  #    name: 'GO import/Fixed export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/GO-VAR-BB-23-02-07/electricity-tariffs/E-1R-GO-VAR-BB-23-02-07-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-BB-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-BB-24-10-26-{octopus_region}/standard-unit-rates/'
  #  - id: 'go_agile'
  #    name: 'GO import/Agile export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/GO-VAR-BB-23-02-07/electricity-tariffs/E-1R-GO-VAR-BB-23-02-07-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-{octopus_region}/standard-unit-rates/'
  #  - id: 'agile_fixed'
  #    name: 'Agile import/Fixed export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-BB-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-BB-24-10-26-{octopus_region}/standard-unit-rates/'
  #  - id: 'agile_agile'
  #    name: 'Agile import/Agile export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-24-10-01/electricity-tariffs/E-1R-AGILE-24-10-01-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-{octopus_region}/standard-unit-rates/'
  #  - id: 'flux'
  #    name: 'Flux import/Export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-IMPORT-23-02-14/electricity-tariffs/E-1R-FLUX-IMPORT-23-02-14-{octopus_region}/standard-unit-rates'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/FLUX-EXPORT-BB-23-02-14/electricity-tariffs/E-1R-FLUX-EXPORT-BB-23-02-14-{octopus_region}/standard-unit-rates'
  #  - id: 'cosy_fixed'
  #    name: 'Cosy import/Fixed export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/COSY-22-12-08/electricity-tariffs/E-1R-COSY-22-12-08-{octopus_region}/standard-unit-rates'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-BB-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-BB-24-10-26-{octopus_region}/standard-unit-rates/'
  #  - id: 'cosy_agile'
  #    name: 'Cosy import/Agile export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/COSY-22-12-08/electricity-tariffs/E-1R-COSY-22-12-08-{octopus_region}/standard-unit-rates'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/AGILE-OUTGOING-BB-23-02-28/electricity-tariffs/E-1R-AGILE-OUTGOING-BB-23-02-28-{octopus_region}/standard-unit-rates/'
  #  - id: 'snug_fixed'
  #    name: 'Snug import/Fixed export'
  #    rates_import_octopus_url: 'https://api.octopus.energy/v1/products/SNUG-24-11-07/electricity-tariffs/E-1R-SNUG-24-11-07-{octopus_region}/standard-unit-rates/'
  #    rates_export_octopus_url: 'https://api.octopus.energy/v1/products/OUTGOING-VAR-BB-24-10-26/electricity-tariffs/E-1R-OUTGOING-VAR-BB-24-10-26-{octopus_region}/standard-unit-rates/'

  # Alert feeds - customise to your country and the alert types, severity and keep value
  #alerts:
  #  url: "https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-united-kingdom"
  #  event: "(Amber|Yellow|Orange|Red).*(Wind|Snow|Fog|Rain|Thunderstorm|Avalanche|Frost|Heat|Coastal event|Flood|Forestfire|Ice|Low temperature|Storm|Tornado|Tsunami|Volcano|Wildfire)"
  #  severity: "Moderate|Severe|Extreme"
  #  certainty: "Possible|Likely|Expected"
  #  keep: 40

  # Watch list, a list of sensors to watch for changes and then update the plan if they change
  # This is useful for things like the Octopus Intelligent Slot sensor so that the plan update as soon as you plugin in
  # Only uncomment the items you actually have set up above in apps.yaml, of course you can add your own as well
  # Note those using +[] are lists that are appended to this list, whereas {} items are single items only
  #watch_list:
  #  - '{octopus_intelligent_slot}'
  #  - '{octopus_ready_time}'
  #  - '{octopus_charge_limit}'
  #  - '{octopus_saving_session}'
  #  - '+[car_charging_planned]'
  #  - '+[car_charging_soc]'
  #  - '{car_charging_now}'
```
